// <auto-generated />
using System;
using LeNguyenKhang_2122110497.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeNguyenKhang_2122110497.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hãng cosplay nổi tiếng Trung Quốc",
                            Name = "DokiDoki",
                            Slug = "dokidoki"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chuyên đồ cosplay anime",
                            Name = "Rolecos",
                            Slug = "rolecos"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hãng tại Trung Quốc",
                            Name = "Manmei",
                            Slug = "manmei"
                        });
                });

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Trang phục Cosplay",
                            Slug = "trang-phuc"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tóc giả (Wig)",
                            Slug = "wig"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phụ kiện & Vũ khí",
                            Slug = "props"
                        });
                });

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.Order_detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Image = "raiden.jpg",
                            Name = "Bộ đồ Raiden Shogun (Genshin Impact)",
                            Price = 1500000m,
                            Slug = "bo-do-raiden-shogun",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            CategoryId = 2,
                            Image = "furina-wig.jpg",
                            Name = "Wig Furina xanh trắng",
                            Price = 450000m,
                            Slug = "wig-furina-xanh-trang",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CategoryId = 3,
                            Image = "IMG_8626.jpg",
                            Name = "Đồ Agnes Tachyon cosplay",
                            Price = 300000m,
                            Slug = "Agnes-Tachyon-cosplay",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CategoryId = 1,
                            Image = "IMG_8601.jpg",
                            Name = "Đồ Gao Red coplay",
                            Price = 1200000m,
                            Slug = "gao-red-cosplay",
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            CategoryId = 2,
                            Image = "IMG_8662.jpg",
                            Name = "Đồ Columbina Cosplay",
                            Price = 500000m,
                            Slug = "do-columbina-cosplay",
                            StockQuantity = 25
                        });
                });

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.Order_detail", b =>
                {
                    b.HasOne("LeNguyenKhang_2122110497.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeNguyenKhang_2122110497.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.Product", b =>
                {
                    b.HasOne("LeNguyenKhang_2122110497.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeNguyenKhang_2122110497.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LeNguyenKhang_2122110497.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
